packages:
  - "packages/*"

allowBuilds:
  "@ast-grep/lang-php": true
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  onnxruntime-node: false
  protobufjs: false
  sharp: false

minimumReleaseAgeExclude:
  - '@netzwerk/cli@0.0.5'
  - '@netzwerk/core@0.0.5'
  - '@netzwerk/php@0.0.5'
  - '@netzwerk/summarize@0.0.5'
  - '@netzwerk/typescript@0.0.5'
  - netzwerk@0.0.5
